# Generated by Django 3.2.2 on 2021-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание вопроса')),
                ('additional_information', models.TextField(verbose_name='Дополнительная информация для пользователя после отправки ответа.')),
                ('image_url', models.CharField(help_text="Загрузите на imgur.com и правым кликом по фото нажмите 'Копировать ссылку на изображение'. Вставьте ссылку\nПример: https://i.imgur.com/uNjl5Rf.jpg", max_length=200, verbose_name='Ссылка на фото')),
                ('video_yt_url', models.CharField(help_text='Вставьте идентификатор видео с YouTube.\nПример: vX3fXef2F4M', max_length=200, verbose_name='Ссылка на видео')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='До какого времени квест можно проходить?')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
