# Generated by Django 3.2.2 on 2021-09-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(help_text="Загрузите на imgur.com и правым кликом по фото нажмите 'Копировать ссылку на изображение'. Вставьте ссылку. Пример: https://i.imgur.com/uNjl5Rf.jpg", max_length=200, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_until',
            field=models.DateTimeField(help_text='До какого времени квест можно проходить?', verbose_name='Время окончания теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_yt_url',
            field=models.CharField(help_text='Вставьте идентификатор видео с YouTube. Пример: vX3fXef2F4M', max_length=200, verbose_name='Ссылка на видео'),
        ),
    ]
