# Generated by Django 3.2.2 on 2021-09-17 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210917_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('question', 'user')},
        ),
    ]
