# Generated by Django 3.2.2 on 2021-09-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_result_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='time_result_done',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда прошёл тест?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
