# Generated by Django 3.2.2 on 2021-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_result_time_result_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image_url', models.CharField(blank=True, help_text="Загрузите на imgur.com и правым кликом по фото нажмите 'Копировать ссылку на изображение'. Вставьте ссылку. Пример: https://i.imgur.com/sRjy27f.jpg", max_length=200, verbose_name='Ссылка на фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Квест создан')),
                ('question', models.ManyToManyField(to='app.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
    ]
