# Generated by Django 3.2.2 on 2021-10-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_url',
            field=models.CharField(help_text="Загрузите на imgur.com и правым кликом по фото нажмите 'Копировать ссылку на изображение'. Вставьте ссылку. Пример: https://i.imgur.com/sRjy27f.jpg", max_length=200, verbose_name='Ссылка на фото'),
        ),
    ]
