# Generated by Django 3.2.2 on 2021-10-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211029_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Выберите 1 правильный ответ для 1 вопроса', verbose_name='Правильный?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_input_question',
            field=models.BooleanField(verbose_name='Отметьте, если ответ на этот вопрос пользователь вводит сам, а не выбирает из «ответов». Потом вам придётся самому выбрать, правильно ли ответил пользователь на вопрос или нет.'),
        ),
        migrations.AlterField(
            model_name='result',
            name='is_correct',
            field=models.NullBooleanField(default=None, verbose_name='Правильно ответил?'),
        ),
    ]
